name: feluq
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyterlab
  - anaconda::ipykernel
  - tensorflow
  - keras
  - pytorch
  - matplotlib
  - pandas
  - pickle5
  - time
  - pip
  - pip:
    - scipy
    - scikit-learn
